enum ModelAlias {
  APPOINTMENTS = 'appointments',
  CITY = 'city',
  CLINIC = 'clinic',
  CLINICS = 'clinics',
  DIAGNOSIS = 'diagnosis',
  DOCTORS = 'doctors',
  DOCTOR = 'doctor',
  DOCUMENT = 'document',
  MESSAGES = 'messages',
  NOTIFICATIONS = 'notifications',
  USER = 'user',
  USERS = 'users',
  GEOLOCATION = 'geolocation',
  PERMISSIONS = 'permissions',
  SPECIALIZATIONS = 'specializations',
  PROFESSION = 'profession',
  PROFESSIONS = 'professions',
}
export { ModelAlias };
