name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install NodeJS v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm run install:all

      - name: BackEnd Build
        run: |
          npm run build:backend

      - name: FrontEnd Build
        working-directory: ./frontend
        run: |
          npm run build
        env:
          REACT_APP_API_ORIGIN_URL: /api/v1

      - name: Move Builds for Deployment
        run: |
          mv backend/build .
          mv frontend/build/* build/public

      - name: Update Heroku Source
        run: |
          git config user.email "${{ secrets.HEROKU_OWNER_EMAIL }}"
          git config user.name "Heroku"
          git add -A
          git commit -m "updated source code"

      - name: Deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_OWNER_EMAIL }}
          appdir: build
